### ISSUE TITLE
Dequeue normalPriorityMessages

### ISSUE THREAD

**Issue by streamchat** [tphx/StreamChatSharp#1]
https://github.com/tphx/StreamChatSharp/blob/47fda222717f0e278bc5a9f04e27e95e971a6c6c/StreamChatSharp/StreamChatSharp/OutgoingMessageQueue.cs#L164

```
        else if (this.normalPriorityMessages.Count > 0)
        {
            ChatMessage message;
            this.highPriorityMessages.TryDequeue(out message);
```

**Comment by tphx** [comment]
Can't believe I missed that. Thank you for the report. Hopefully all is good now.
